apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: outlier-detection-deployment
spec:
  concurrencyPolicy: Forbid
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ml
            image: suhaib24/ml-gracc-outlier-detection
            env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gracc-outlier-secret
                  key: username
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gracc-outlier-secret
                  key: password
          restartPolicy: OnFailure